### ISSUE TITLE
I18N does not contain a definition for 'ChangeLocale'

### ISSUE THREAD

**Issue by drunkendaddy** [kvandake/friendly-locale#8]
can't use the library

**Comment by kvandake** [comment]
I18N.Instance.ChangeLocale()

II18N.cs - https://github.com/kvandake/friendly-locale/blob/master/FriendlyLocale/II18N.cs#L87
I18N.cs - https://github.com/kvandake/friendly-locale/blob/master/FriendlyLocale.Shared/I18N.cs#L12
